In [2]:
import numpy as np

In [3]:
my_list1 = [1,2,3,4]

In [4]:
my_array1 = np.array(my_list1)

In [5]:
my_array1

array([1, 2, 3, 4])

In [6]:
my_list2 = [11,22,33,44]

In [7]:
my_lists = [my_list1,my_list2]

In [8]:
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [9]:
my_array2 = np.array(my_lists)

In [10]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [11]:
my_array2.shape

(2, 4)

In [12]:
my_array2.dtype

dtype('int64')

In [13]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [14]:
my_zeros = np.zeros(5)

In [15]:
my_zeros.dtype

dtype('float64')

In [16]:
np.ones((5.5))

TypeError: 'float' object cannot be interpreted as an integer

In [17]:
np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [18]:
np.empty

<function numpy.core.multiarray.empty>

In [19]:
np.empty((3,4))

array([[ -3.10503618e+231,  -3.11109526e+231,   2.96439388e-323,
          0.00000000e+000],
       [  2.12199579e-314,   4.47032019e-038,   5.94604830e-091,
          1.39380322e+165],
       [  8.40871251e+164,   3.22115228e-057,   3.99910963e+252,
          8.34402701e-309]])

In [20]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [21]:
np.arrange(5
)

AttributeError: module 'numpy' has no attribute 'arrange'

In [22]:
np.arrange(5)

AttributeError: module 'numpy' has no attribute 'arrange'

In [23]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [24]:
np.arange(5,50,3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [1]:
5/2

2.5

In [2]:
from __future__ import division

In [3]:
arr1 = np.array([1,2,3,4],[8,9,10,11])

NameError: name 'np' is not defined

In [4]:
import numpy as np

In [5]:
arr1 = np.array([1,2,3,4],[8,9,10,11])

TypeError: data type not understood

In [6]:
arr1 = np.array([[1,2,3,4],[8,9,10,11]])

In [7]:
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [8]:
arr1 * arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [9]:
arr1 - arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [10]:
1 / arr1

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.125     ,  0.11111111,  0.1       ,  0.09090909]])

In [11]:
arr1 ** 3

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]])

In [12]:
arr = np.arange(0,11)

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr[8]

8

In [15]:
arr[1:5]

array([1, 2, 3, 4])

In [16]:
arr[0:5] = 100

In [17]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [18]:
sli_arr[:] = 99

NameError: name 'sli_arr' is not defined

In [19]:
slice_arr[:] = 99

NameError: name 'slice_arr' is not defined

In [20]:
slice_arr[:] = arr(0:6)

SyntaxError: invalid syntax (<ipython-input-20-d45338fd8139>, line 1)

In [21]:
slice_arr[:] = arr[0:6]

NameError: name 'slice_arr' is not defined

In [22]:
slice_arr = arr[0:6]

In [23]:
slice_arr

array([100, 100, 100, 100, 100,   5])

In [24]:
slice_arr[:] = 99

In [25]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [26]:
arr.copy = arr.copy()

AttributeError: 'numpy.ndarray' object attribute 'copy' is read-only

In [27]:
arr_copy = arr.copy()

In [28]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [29]:
arr_2s

NameError: name 'arr_2s' is not defined

In [30]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [31]:
arr_2d[1][0]

20

In [32]:
arr_2d[0,0]

5

In [33]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [34]:
arr_2d = np.zeros((10,10))

In [35]:
arr2d

NameError: name 'arr2d' is not defined

In [36]:
arr_2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [37]:
arr_length = arr_2d.shape[1]

In [38]:
for i in range(arr_length):
    arr_2d[i] = i

In [39]:
arr_2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

In [40]:
arr = np.arrange(9).reshape((3,3))

AttributeError: module 'numpy' has no attribute 'arrange'

In [41]:
import numpy as np

In [42]:
arr = np.arrange(9).reshape((3,3))

AttributeError: module 'numpy' has no attribute 'arrange'

In [43]:
arr = np.arange(9).reshape((3,3))

In [44]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [45]:
arr.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [46]:
arr.transpose()

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [47]:
arr.transpose((0,1))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [48]:
arr.transpose((1,0))

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [49]:
arr.swapaxes(0,1)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [50]:
np.dot

<function numpy.core.multiarray.dot>

In [51]:
np.dot(arr.T,arr)

array([[45, 54, 63],
       [54, 66, 78],
       [63, 78, 93]])

In [52]:
arr3d = np.arange(12).reshape((3,2,2))

In [53]:
arr3d

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [54]:
arr[0]

array([0, 1, 2])

In [55]:
arr3d[0]

array([[0, 1],
       [2, 3]])

In [56]:
arr3d.transpose((0,2,1))

array([[[ 0,  2],
        [ 1,  3]],

       [[ 4,  6],
        [ 5,  7]],

       [[ 8, 10],
        [ 9, 11]]])

In [57]:
import numpy as np

In [58]:
arr= np.arange(11)

In [59]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [60]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [61]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [62]:
A = np.random.randn(10)

In [63]:
A

array([-0.98798205, -0.86475614, -0.364613  ,  1.67797032, -0.84069672,
       -0.15279222,  0.35055319,  0.78547863, -0.51001577,  1.77309857])

In [64]:
B = np.random.randn(10)

In [65]:
np.add(A,B)

array([-1.88594948, -1.96802   ,  0.04293266,  2.14092896, -2.03314574,
        1.0916365 ,  1.52348536,  0.70000929,  1.38207735,  2.09361806])

In [66]:
np.maximum(A,B)

array([-0.89796743, -0.86475614,  0.40754566,  1.67797032, -0.84069672,
        1.24442872,  1.17293216,  0.78547863,  1.89209312,  1.77309857])

In [67]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

ModuleNotFoundError: No module named 'matplotlib'

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
points = np.arange(-5,5,0.01)

In [ ]:
dx,dy = np.mesggrid(points,points)

In [ ]:
dx


In [ ]:
dx

In [ ]:
dx, dy = np.meshgrid(points points)

In [ ]:
dx

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
points = np.arange(-5,5,0.01)

In [ ]:
dx,dy = np.mesggrid(points,points)

In [ ]:
dx